name: Build Datapack
run-name: Datapack release triggered by ${{ github.actor }}
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    Create-Artifact:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: checkout
              uses: "actions/checkout@v4"
            - name: export
              run: git archive -o fishers-finders.zip HEAD
            - name: release
              uses: softprops/action-gh-release@v2
              with:
                files: fishers-finders.zip
            